language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update -qq

install:
  - >
    sudo apt-get install -qq
    libboost-program-options-dev
    libpcp3 libpcp3-dev libpcp-pmda3 libpcp-pmda3-dev
  - sudo pip install cpp-coveralls --use-mirrors

before_script:
  - mkdir -p build

script:
  - pushd build
  - cmake .. && make check
  - popd

after_success:
  - coveralls -e example --verbose | tr ',' '\n' | grep "'name':" | sort
  - coveralls -e example -E '.+build.*\.(cc?|h)' -E '.+test.*\.cpp' --verbose
