language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update -qq

install:
  - >
    sudo apt-get install -qq
    libboost-program-options-dev
    libpcp3 libpcp3-dev libpcp-pmda3 libpcp-pmda3-dev
    rubygems
  - if [ "$CXX" = "g++" ]; then sudo apt-get install lcov; fi
  - sudo pip install cpp-coveralls --use-mirrors
  - gem install lcoveralls --pre

before_script:
  - mkdir -p build

script:
  - pushd build
  - cmake .. && make check
  - if [ "$CXX" = "g++" ]; then make coverage; fi
  - popd

after_success:
  - pwd
  - find . -name *.info
  - if [ "$CXX" = "g++" ]; then lcoveralls --trace; fi
  - git status
