language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq libboost-program-options-dev libpcp3 libpcp3-dev libpcp-pmda3 libpcp-pmda3-dev
  - sudo apt-get install -qq valgrind

before_script:
  - mkdir -p test/unit/build

script:
  # Run the unit tests.
  - pushd test/unit/build
  - cmake .. && make && valgrind ./test
  - cmake .. && make check
  - popd
  # Ensure the examples compile cleanly.
  - make -C example
