language: cpp

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-program-options-dev libpcp3-dev libpcp-pmda3-dev
  - grep -Ir PM_MAXERRMSGLEN /usr/include/pcp/
  - grep -Ir 128 /usr/include/pcp/

compiler:
  #- clang
  - gcc

script:
  # Just building the examples for now; no real tests to speak of yet.
  - make -C example
