language: cpp

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-program-options-dev libpcp3-dev libpcp-pmda3-dev
  - readelf -Ws /usr/lib/libpcp.so || true
  - readelf -Ws /usr/lib/libpcp.so | grep pmNotifyErr || true
  - readelf -Ws /usr/lib/libpcp_pmda.so || true
  - readelf -Ws /usr/lib/libpcp_pmda.so | grep pmNotifyErr || true
  - false

compiler:
  #- clang
  - gcc

script:
  # Just building the examples for now; no real tests to speak of yet.
  - make -C example
